services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  mariadb:
    image: mysql:9.2.0
    container_name: mysql-test-container
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=products
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3307:3306"

